plugins {
    // see https://maven.fabricmc.net/fabric-loom/fabric-loom.gradle.plugin/maven-metadata.xml for new versions
    id 'net.fabricmc.fabric-loom' version '1.18.1' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.147' apply false

    id "io.github.pacifistmc.forgix" version "2.0.0"
}

forgix {
    fabric()
    neoforge()

    destinationDirectory = layout.projectDirectory.dir("build/forgix")
    archiveClassifier = "universal"
}

tasks.named("mergeJars") {
    dependsOn(":fabric:jar", ":neoforge:jar")
}

// go stuff
def minetailcatgo = file("$rootDir/minetailcat-go")
def nativeOutputDir = file("$projectDir/common/src/main/resources/native")

def goosList = [:]
goosList["linux"] = ["amd64","arm64"]
goosList["windows"] = ["amd64","arm64"]
goosList["darwin"] = ["amd64","arm64"]

def allTasks = []

goosList.each { goos,archs ->
    archs.each{ arch ->
        def taskName = "buildHelper${goos.capitalize()}${arch.capitalize()}"
        def ext = goos=="windows" ? ".exe":""

        def output = file("$nativeOutputDir/${goos}/minetailcat_${arch}${ext}")

        def task = tasks.register(taskName, Exec) {
            group = "tailcat"
            description = "build Minetailcat helper for ${goos} ${arch}"

            workingDir(minetailcatgo)

            // https://akrabat.com/building-go-binaries-for-different-platforms/
            // https://go.dev/doc/install/source#environment
            environment("GOOS", goos)
            environment("GOARCH", arch)
            environment("CGO_ENABLED", "0") // cross compile needs this?

            commandLine("go","build","-o",output.absolutePath,".")

            inputs.files(fileTree(minetailcatgo) {
                include "**/*.go"
                include "go.mod"
                include "go.sum"
            })

            outputs.file(output)
        }

        allTasks.add(task)
    }
}

tasks.register("buildHelpers") {
    group = "tailcat"
    description = "make minetailcat helper for all goTargets"
    dependsOn(allTasks)
}

subprojects {
    // idk if this is the right way to hook into the build process
    tasks.matching { it.name == "processResources" }.configureEach {
        dependsOn(rootProject.tasks.named("buildHelpers"))
    }
}